name: kubernetes
columns:
- Tested dlv
- note
versions:
- version: v1.35.1
  artifacts:
  - binary: kubelet-v1.35.1-debug
    dlv: v1.25.1~v1.26.1
    note: ''
  - binary: kubectl-v1.35.1-debug
    dlv: ''
    note: ''
- version: v1.33.8
  artifacts:
  - binary: kubelet-v1.33.8-debug
    dlv: ''
    note: ''
- version: v1.32.2
  artifacts:
  - binary: kubelet-v1.32.2-debug
    dlv: v1.24.1~v1.25.2
    note: ''
